Created toolbar and headline
CesarHerr/portfolio pull request #1
Opened 2023-03-23 21:20 UTC by CesarHerr

Setup Mobile First

- Added linters.
-  Added HTML and CSS files.
- Created a toolbar.
- Created a headline section.

2023-03-23 21:45 UTC, Shisui6 requested changes
Hi @CesarHerr , 

# Requires Changes 🍀
You have done a great job so far!
Your design is good 🖼️, and your code follows best practices. However, there are a few issues that you still need to work on🪲.

## Highlights
- Dood use of sematic tags ✅
- Good design ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 21:45 UTC, Shisui6 commented on index.html
> +                <li><h3 class="nav-info">Contact</h3></li> -->
Please do not leave commented out pieces of code in your project. This makes your code look messy and violates the [DRY](https://www.techtarget.com/whatis/definition/DRY-principle) principle of coding🙏.

2023-03-23 21:45 UTC, Shisui6 commented on index.html
> +        <p class="logo-header">My logo</p>
Kindly wrap your logo in an `<a>` tag🙏. Typically, the logo links to the homepage of a website. This action helps improve user experience

2023-03-23 21:45 UTC, Shisui6 commented on css/styles.css
> +}
Kindly reduce the height of your toolbar so it matches the figma design better🙏

Your design:
<img width="202" alt="image" src="https://user-images.githubusercontent.com/37116322/227367981-3796c247-9b1f-47fe-a8ca-66214f088c80.png">


Figma design:
<img width="278" alt="image" src="https://user-images.githubusercontent.com/37116322/227368027-3c06ebad-38ea-411e-ad9a-716a2a2a67e7.png">

2023-03-23 21:45 UTC, Shisui6 commented on index.html
> +            <img src="/images/Group.svg" alt="image-vectors">
Kindly add this image as a background image instead of using an `<img>` tag🙏. Images that are part of the background are purely decorative, so they should be styled as background images🎨. Also, with your current implementation, you may definitely run into issues if you leave it this way when styling the upcoming sections

2023-03-23 21:45 UTC, Shisui6 commented on index.html
> +            </div>
Kindly update your list of social links to be wrapped in a `<ul>` tag instead of a `<div>` tag. This is for semantic reasons as ul tags are used to wrap most lists in a webpage

- In addition to that, please wrap each img in a `<li>` tag and make sure that the images are all links using an `<a>` tag. Your final code should look similar to something like this
`<ul>`
     `<li><a><img/></a></li>`
     `<li><a><img/></a></li>`
     `<li><a><img/></a></li>`
`</ul>`

2023-03-23 21:45 UTC, Shisui6 commented on index.html
> +    <link rel="stylesheet" href="/css/styles.css">
Your images and styles are currently not being applied in the browser😥. I believe the problem stems from the path you're specifying to all your files. kindly update all your file paths to use relative paths by adding a `.` before the file path E.G `"./css/styles.css"`🙏. This includes stylesheets and all your images. This way your styles will be applied on whichever platform your project is opened on👍.

<img width="211" alt="image" src="https://user-images.githubusercontent.com/37116322/227370330-3049a740-5633-4052-a313-96fa52e79424.png">


**Please note: Your project may look fine when using live server but if simply opened in the browser, no styles are applied**

2023-03-23 21:45 UTC, Shisui6 commented on css/styles.css
> +}
Kindly reduce the font-weight of the main title and subtitle to match the figma design better:

Your design:
<img width="210" alt="image" src="https://user-images.githubusercontent.com/37116322/227370897-cf12fe22-fc57-4581-8b9a-3788ada26497.png">

Figma design:
<img width="182" alt="image" src="https://user-images.githubusercontent.com/37116322/227370997-48890497-760c-4f7f-a720-18b2d1511a3f.png">

2023-03-24 01:08 UTC, franclobo approved these changes
Hi @CesarHerr, 

# STATUS: APPROVED 😃 

![git-merge](https://user-images.githubusercontent.com/58642949/227398525-c0696bb2-d88a-4eda-8272-6933a79e2d74.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 
- Good UI 💯 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 01:08 UTC, franclobo commented on css/styles.css
> +  background-image: url(/images/Group.svg);
- **[OPTIONAL]** Well done replacing the image for a background image, but please 🙏🏽 use the correct path of the image 👉🏽 `url(../images/Group.svg)` to be 100% similar to the Figma design.

2023-03-24 01:21 UTC, CesarHerr commented on css/styles.css
> +  background-image: url(/images/Group.svg);
😄 Thank you very much for your feedback @franclob 🥇   , I will do the change you suggest 🆗

2023-03-24 01:28 UTC, merged